package com.tripadvisor.reflow;

/**
 * An object that manages the actual execution of tasks,
 * scheduling new tasks and signaling the completion of tasks via callback.
 *
 * <p>Scheduling a task yields a token object that represents the newly
 * scheduled task instance. Tokens can be used to register additional
 * callbacks at a later time, and must remain valid at least until the
 * associated task is completed.</p>
 *
 * <p>Scheduler instances may accept tokens generated by a different instance.
 * </p>
 */
public interface TaskScheduler<T>
{
    /**
     * Schedules a task and registers a callback object that will be used to
     * signal the completion of the task, successful or not. The callback may
     * be invoked directly by this method or in another thread after this
     * method returns.
     *
     * <p>Returns a non-null token representing the scheduled task instance.</p>
     */
    ScheduledTaskToken submit(T task, TaskCompletionCallback callback);

    /**
     * Given a token representing a scheduled task instance, registers a
     * callback object that will be used to signal the completion of the task,
     * successful or not. If the task has already been completed, immediately
     * invokes a callback method.
     *
     * @throws InvalidTokenException if {@code token} does not correspond to a
     * scheduled task instance
     */
    void registerCallback(ScheduledTaskToken token, TaskCompletionCallback callback) throws InvalidTokenException;
}
